### ISSUE TITLE
Need fonts to support GUI anaconda

### ISSUE THREAD

**Issue by sgallagher** [modularity-modules/fonts#1]
We need enough fonts to support anaconda with graphical install for Fedora 27 Server Edition. Right now, there are almost none.

**Comment by KarstenHopp** [comment]
Is this ok now or are there still missing fonts ?

**Comment by sgallagher** [comment]
There are still missing fonts. See https://bugzilla.redhat.com/show_bug.cgi?id=1506840

**Comment by KarstenHopp** [comment]
This is fixed and the bugzilla got closed.
